files:
  # This can be named anything that makes sense to you. But it has to include
  # the following properties:
  #   directory: the directory to watch
  #   change: change to watch for (modification, creation). Modification
  #           includes creation.
  #   pattern [optional]: a glob pattern to filter the files to be watched.
  #           defaults to *
  important_files:
    directory: /opt/stuff/important/
    change: modification
  somewhat_important_texts:
    directory: /opt/stuff/less_important/
    change: creation
    pattern: '*.txt'

notifications:
  # Period of notification in hours.
  #   Accepts fraction of hours: 0.5 -> half an hour
  #   If omitted, notifications are sent as soon as they occur
  period: 1
  # List of notification receivers
  email_receivers: [example@example.com, example2@mydomain.com]
