[cosmic-ray]
module-path = "src"
python-version = ""
timeout = 10
exclude-modules = []
test-command = "poetry run pytest -x test"

[cosmic-ray.execution-engine]
name = "local"

[cosmic-ray.cloning]
method = "copy"
commands = ["poetry install"]
